# Generated by Django 4.1 on 2022-09-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_content', models.CharField(max_length=50)),
                ('negative', models.IntegerField()),
            ],
        ),
    ]
